# Generated by Django 2.0.6 on 2020-03-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='pic',
            field=models.ImageField(upload_to='media'),
        ),
    ]
