# Generated by Django 2.0.6 on 2020-03-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200305_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
