# Generated by Django 2.0.6 on 2020-03-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_banner_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='pic',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
